server:
  port: 8081
logging:
  pattern:
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
  file:
    name: application.log
  level:
    root: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
    username: root
    password: 7758521
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: false
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.pcl.spring.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl